services:
  magic-platform:
    env_file:
      - .env.dev
    build:
      context: .
    command: /app/run_app.sh mage start $PROJECT_NAME
    ports:
      - 6789:6789
    volumes:
      - .:/$MAGE_CODE_PATH  # Mount your local codebase to the container.
      - ~/.mage_data:/$MAGE_CODE_PATH/mage_data # Store the data output on local machine to easily debug (optional).
      - ~/.aws:/root/.aws # Initial credentials to create an IAM user with limited permissions for deployment.
      - ~/.ssh:/root/.ssh:ro  # Local machine’s SSH keys to pull and push to your GitHub repository.
      - ~/.gitconfig:/root/.gitconfig:ro  # Local machine’s GitHub configs
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  # MLflow tracking URI  
    restart: on-failure:5
    networks:
      - app-network
    depends_on:
      - magic-database
    stdin_open: true # used for interactive debugging
    tty: true # used for interactive debugging
  magic-database:
    image: pgvector/pgvector:0.6.0-pg16
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    volumes:
      - ~/.postgres/data:/var/lib/postgresql/data
      # Custom database initialization scripts (optional).
      - ./scripts/database:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app-network
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow/mlflow.db
    command: mlflow server --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root /mlflow/artifacts -h 0.0.0.0
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
    restart: always
    networks:
      - app-network
      - front-end
networks:
  app-network:
    driver: bridge
  front-end: